language: bash

os: osx

addons:
  homebrew:
    packages:
    - macvim
    - tmux

before_script:
  - sudo chmod +x install/bootstrap.sh
  
script:
  - printf 'O\n' | install/bootstrap.sh --skip-git
